name: Test Custom Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run the custom action
        uses: amarsingh3d/action-convert-fpr@main  # Reference your custom action  
        with:
          fpr_file: 'latest.fpr'
      - name: Debug output files  
        run: |
          ls -l 
          

      - name: Read output file
        id: read-output
        run: |
          cat output.txt | tee extracted_output.txt

          
