name: Test Custom Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run the custom action
        uses: amarsingh3d/action-convert-fpr@main  # Reference your custom action  
        with:
          fpr_file: 'latest.fpr'
          output_path: 'output.txt'

      - name: Read output file
        id: read-output
        run: |
          cat output.txt | tee extracted_output.txt

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('extracted_output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Vulnerability Report\\n\\n${output}`
            });

          
