name: Use Custom Action

on:
  workflow_dispatch:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom action
        uses: amarsingh3d/action-convert-fpr@main  # Reference your custom action
        with:
          fpr_file: 'latest.fpr'
          output_csv: 'output.csv'
