name: Test Custom Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

permissions:
  contents: read
  pull-requests: write
  issues: write


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run the custom action
        uses: amarsingh3d/action-convert-fpr@main  # Reference your custom action  
        with:
          fpr_file: 'latest.fpr'
          output_path: 'output.txt'

      - name: Read output file
        id: read-output
        run: |
          cat output.txt | tee extracted_output.txt

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
      
            // Read the raw table from the output file
            const rawOutput = fs.readFileSync('extracted_output.txt', 'utf8');
      
            // Transform the raw table into Markdown syntax
            const lines = rawOutput.split('\n');
            const header = '| Kingdom        | Type                      | Subtype   | Severity | SourceLocation                                   |';
            const separator = '|----------------|---------------------------|-----------|----------|-------------------------------------------------|';
            
            // Filter and clean up the rows, skipping duplicate header rows
            const dataRows = lines
              .filter(line => line.startsWith('|') && !line.includes('=') && !line.includes('Kingdom'));
      
            const markdownTable = [header, separator, ...dataRows].join('\n');
      
            // Create the comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### HP Fortify Vulnerability Scan Report\n\n${markdownTable}`
            });
