name: Find Repos Containing Dockerfile

on:
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  search-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Install GitHub CLI (if not installed)
        run: |
          if ! command -v gh &> /dev/null; then
            echo "GitHub CLI not found. Installing..."
            sudo apt-get update
            sudo apt-get install gh -y
          else
            echo "GitHub CLI is already installed."
          fi          
    

      - name: Authenticate with GitHub CLI
        run: |
          echo "Authenticating with GitHub CLI"
          echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token

      - name: Get repositories in the organization
        id: repos
        run: |
          # Fetch list of repositories and save them to a file
          gh repo list amarsingh3d --json name -L 500 --limit 500 | jq -r '.[].name' > repos.txt
          # Output the contents of repos.txt for debugging
          cat repos.txt

      - name: Search for Dockerfile in each repo
        id: search-dockerfile
        run: |
          # Read repos from the file and search for Dockerfile
          while IFS= read -r REPO; do
            echo "Searching in repo: $REPO"
