name: Find Repos Containing Dockerfile

on:
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  search-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Install GitHub CLI (if not installed)
        run: |
          if ! command -v gh &> /dev/null; then
            echo "GitHub CLI not found. Installing..."
            sudo apt-get update
            sudo apt-get install gh -y
          else
            echo "GitHub CLI is already installed."
          fi
          
      - name: Set up GitHub CLI
        uses: cli/cli@v2
        with:
          version: '2.x'

      - name: Authenticate with GitHub CLI
        run: |
          echo "Authenticating with GitHub CLI"
          echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token

      - name: Get repositories in the organization
        id: repos
        run: |
          REPOS=$(gh repo list <your-org-name> --json name -L 500 --limit 500 | jq -r '.[].name')
          echo "REPOS=$REPOS" >> $GITHUB_ENV

      - name: Search for Dockerfile in each repo
        id: search-dockerfile
        run: |
          for REPO in $REPOS; do
            echo "Searching in repo: $REPO"
            FILES=$(gh repo view <your-org-name>/$REPO --json files --jq '.files[].name' | grep -i Dockerfile)
            if [[ ! -z "$FILES" ]]; then
              echo "$REPO contains a Dockerfile"
            fi
          done
