name: Semiannual PR Creation

on:
  workflow_dispatch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token

      - name: Get all repositories and create PRs
        env:
          ORG_NAME: amarsingh3d
        run: |
          # Fetch all organization repositories
          repos=$(gh repo list $ORG_NAME --limit 500 --json name -q '.[].name')

          # Loop through each repo and create a PR
          for repo in $repos; do
            echo "Processing $repo..."
            
            # Get the default branch of the repository
            default_branch=$(gh repo view $ORG_NAME/$repo --json defaultBranchRef -q '.defaultBranchRef.name')
            echo "Default branch for $repo is $default_branch"

            # Clone the repository
            gh repo clone $ORG_NAME/$repo
            cd $repo

            # Setup Git user
            git config --global user.email "${{ secrets.GIT_EMAIL }}"
            git config --global user.name "${{ secrets.GIT_USER }}"
            git remote set-url origin https://${{ secrets.GIT_TOKEN }}@github.com/$ORG_NAME/$repo.git

            # Create a new branch
            git checkout -b semiannual-update

            # Make changes to files (e.g., update README or add a version tag)
            echo "Semiannual update - $(date)" >> README.md
            git add README.md
            git commit -m "Semiannual update"

            # Remove the remote branch if it exists
            git push origin --delete semiannual-update || true

            # Push the branch to the repository
            git push origin semiannual-update --force

            # Create the PR, using the default branch as base
            gh pr create --title "Semiannual Update" --body "Automated semiannual update" --base $default_branch --head semiannual-update

            cd ..
            rm -rf $repo # Clean up
          done
