name: Semiannual PR Creation

on:
  workflow_dispatch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token

      - name: Get all repositories and create PRs
        env:
          ORG_NAME: amarsingh3d
        run: |
          # Fetch all organization repositories
          repos=$(gh repo list $ORG_NAME --limit 500 --json name -q '.[].name')

          # Loop through each repo and create a PR
          for repo in $repos; do
            echo "Processing $repo..."

            # Clone the repository
            gh repo clone $ORG_NAME/$repo
            cd $repo

            # Create a new branch
            git checkout -b semiannual-update

            # Make changes to files (e.g., update README or add a version tag)
            echo "Semiannual update - $(date)" >> README.md
            git add README.md
            git commit -m "Semiannual update"

            # Push the branch and create a PR
            git push origin semiannual-update
            gh pr create --title "Semiannual Update" --body "Automated semiannual update" --base main --head semiannual-update

            cd ..
            rm -rf $repo # Clean up
          done
